"use client";

import { useEffect, useState } from "react";
import { deleteAllExpenses, defaultSettings, getExpenses, getSettings, saveSettings, type CurrencyCode } from "@/lib/firebase/expenses";
import { useTheme } from "@/components/ThemeProvider";

const categoryPalette = [
  { dot: "bg-indigo-500", chip: "border-indigo-200 bg-indigo-50 text-indigo-800 dark:border-indigo-800 dark:bg-indigo-950/50 dark:text-indigo-200" },
  { dot: "bg-orange-400", chip: "border-orange-200 bg-orange-50 text-orange-800 dark:border-orange-800 dark:bg-orange-950/50 dark:text-orange-200" },
  { dot: "bg-emerald-500", chip: "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-800 dark:bg-emerald-950/50 dark:text-emerald-200" },
  { dot: "bg-amber-400", chip: "border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-800 dark:bg-amber-950/50 dark:text-amber-200" },
  { dot: "bg-rose-400", chip: "border-rose-200 bg-rose-50 text-rose-800 dark:border-rose-800 dark:bg-rose-950/50 dark:text-rose-200" },
  { dot: "bg-sky-500", chip: "border-sky-200 bg-sky-50 text-sky-800 dark:border-sky-800 dark:bg-sky-950/50 dark:text-sky-200" },
];

export default function SettingsPage() {
  const { dark, setDark } = useTheme();
  const [currency, setCurrency] = useState<CurrencyCode>(defaultSettings.currency);
  const [budget, setBudget] = useState("0");
  const [categories, setCategories] = useState(defaultSettings.categories);
  const [newCategory, setNewCategory] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [showConfirm, setShowConfirm] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => { getSettings().then((settings) => { setCurrency(settings.currency); setBudget(String(settings.monthlyBudget || "")); setCategories(settings.categories); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Unable to load settings.")); }, []);

  const save = async (values: { currency?: CurrencyCode; monthlyBudget?: number; categories?: string[] }) => {
    setError("");
    try { await saveSettings(values); setMessage("Settings saved."); window.setTimeout(() => setMessage(""), 2200); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Unable to save settings."); }
  };

  const addCategory = async () => { const name = newCategory.trim(); if (!name || categories.some((item) => item.toLowerCase() === name.toLowerCase())) return; const next = [...categories, name]; setCategories(next); setNewCategory(""); await save({ categories: next }); };
  const removeCategory = async (name: string) => { const expenses = await getExpenses(); if (expenses.some((expense) => expense.category.toLowerCase() === name.toLowerCase())) { setError("Categories in use cannot be removed."); return; } const next = categories.filter((item) => item !== name); setCategories(next); await save({ categories: next }); };
  const confirmDelete = async () => { setIsDeleting(true); setError(""); try { await deleteAllExpenses(); setShowConfirm(false); setMessage("All expenses deleted."); } catch (deleteError) { setError(deleteError instanceof Error ? deleteError.message : "Unable to delete expenses."); } finally { setIsDeleting(false); } };

  return <main className="min-h-[calc(100vh-72px)] bg-slate-50 px-4 py-8 dark:bg-slate-950 sm:px-8 sm:py-12"><div className="mx-auto max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-indigo-600">Configuration</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white">Settings</h1><p className="mt-2 max-w-xl text-slate-600 dark:text-slate-300">Set up the money preferences and categories that make your tracker feel like yours.</p>{message && <p role="status" className="mt-5 rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300">{message}</p>}{error && <p role="alert" className="mt-5 rounded-2xl border border-rose-100 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}
    <div className="mt-8 space-y-5">
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">Money setup</p><h2 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Money preferences</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700 dark:text-slate-200">Currency<select value={currency} onChange={(event) => { const value = event.target.value as CurrencyCode; setCurrency(value); void save({ currency: value }); }} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 font-normal outline-none transition focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 dark:border-slate-700 dark:bg-slate-800"><option value="USD">USD $</option><option value="PKR">PKR ₨</option><option value="INR">INR ₹</option><option value="EUR">EUR €</option></select></label><label className="text-sm font-semibold text-slate-700 dark:text-slate-200">Monthly budget<input type="number" min="0" value={budget} onChange={(event) => setBudget(event.target.value)} onBlur={() => void save({ monthlyBudget: Number(budget) || 0 })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 font-normal outline-none transition focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 dark:border-slate-700 dark:bg-slate-800" placeholder="0.00" /><span className="mt-1.5 block text-xs font-normal leading-5 text-slate-500 dark:text-slate-400">This powers the Remaining Budget card on your Dashboard.</span></label></div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">Personalize</p><h2 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Categories</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Use labels that match the way you spend.</p></div><div className="mt-5 flex gap-2"><input aria-label="New category" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void addCategory(); } }} placeholder="Add a category" className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-slate-50 px-3.5 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 dark:border-slate-700 dark:bg-slate-800" /><button type="button" onClick={() => void addCategory()} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-500">Add</button></div>{categories.length > 0 ? <div className="mt-5 flex flex-wrap gap-2">{categories.map((item, index) => { const palette = categoryPalette[index % categoryPalette.length]; return <div key={item} className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm font-medium ${palette.chip}`}><span aria-hidden="true" className={`h-2 w-2 rounded-full ${palette.dot}`} />{item}<button type="button" aria-label={`Remove ${item}`} title={`Remove ${item}`} onClick={() => void removeCategory(item)} className="ml-0.5 flex h-5 w-5 items-center justify-center rounded-full text-base leading-none opacity-60 transition hover:bg-black/10 hover:opacity-100">×</button></div>; })}</div> : <div className="mt-5 rounded-2xl border border-dashed border-slate-200 px-4 py-6 text-center dark:border-slate-700"><p className="text-sm font-medium text-slate-600 dark:text-slate-300">No categories yet</p><p className="mt-1 text-xs text-slate-400">Add one above to organize your expenses.</p></div>}</section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">Interface</p><h2 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Appearance</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Use a darker palette for evening reviews.</p></div><button type="button" role="switch" aria-checked={dark} onClick={() => setDark(!dark)} className={`relative h-7 w-12 shrink-0 rounded-full transition ${dark ? "bg-indigo-600" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition-transform ${dark ? "translate-x-6" : "translate-x-1"}`} /></button></div></section>
      <section className="rounded-3xl border border-rose-200 bg-white p-5 shadow-sm dark:border-rose-900 dark:bg-slate-900 sm:p-7"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-rose-100 text-lg text-rose-600 dark:bg-rose-950/60 dark:text-rose-300">!</div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-rose-600 dark:text-rose-400">Irreversible actions</p><h2 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Danger zone</h2><p className="mt-1 max-w-lg text-sm leading-5 text-slate-500 dark:text-slate-400">Permanently remove every expense from database. Your settings and categories will remain.</p></div></div><button type="button" onClick={() => setShowConfirm(true)} className="mt-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-semibold text-rose-700 transition hover:bg-rose-100 dark:border-rose-800 dark:bg-rose-950/40 dark:text-rose-300 dark:hover:bg-rose-950/70">Delete all data</button></section>
    </div></div>{showConfirm && <div role="dialog" aria-modal="true" aria-labelledby="delete-title" aria-describedby="delete-description" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-6 shadow-2xl dark:border-slate-700 dark:bg-slate-900"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-rose-100 text-xl text-rose-600 dark:bg-rose-950/60 dark:text-rose-300">!</div><h2 id="delete-title" className="mt-4 text-xl font-bold text-slate-900 dark:text-white">Delete all expenses?</h2><p id="delete-description" className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">This permanently removes every recorded expense. Your currency, budget, and categories will not be changed.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={() => setShowConfirm(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Cancel</button><button type="button" disabled={isDeleting} onClick={() => void confirmDelete()} className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-rose-500 disabled:cursor-not-allowed disabled:opacity-60">{isDeleting ? "Deleting..." : "Yes, delete everything"}</button></div></div></div>}</main>;
}
